# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f29006574df261bd1aea1e9d03312ea95578024d27f984f55be77f8db2b4be42f9ce97f8624ccd3a8e3ed0f2d1de2398a394ffb4ac51dc49e2b61ed27650fd9d

test:
  secret_key_base: 908241508d0699f8bb4c10de603793ac5fb0715d6c6f025008fe28b3d1b23c168c9ce7f79892b710a5e9d48e0e1c0d0f88ed28f6796580daa70963ee427d49d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
